development:
  :server: "imap.server.de"
  :port: 993
  :ssl: true
  :mail_address: "service@mail"
  :password: "password"
  :sender_mailbox: "device"
  :sender_host: "domain"

test:
  :server: "imap.server.de"
  :port: 993
  :ssl: true
  :mail_address: "service@mail"
  :password: "password"
  :sender_mailbox: "device"
  :sender_host: "domain"

production:
  :server: "imap.server.de"
  :port: 993
  :ssl: true
  :mail_address: "service@mail"
  :password: "password"
  :sender_mailbox: "device"
  :sender_host: "domain"
