name: CI

on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ github-actions ]
  #pull_request:
   # branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
       # define which steps to run
       BUILD: ${{ false }}
       RUBY_UNIT: ${{ true }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: build  
        if: env.BUILD == 'true'
        run: |
            gem install bundler -v 1.17.3
      - name: ruby unit test
        if: env.RUBY_UNIT == 'true'
        run: |
            echo $RUBY_UNIT
            RAILS_ENV=test bundle exec rake db:schema:load

