name: CI

on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ github-actions ]
  #pull_request:
   # branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
       # define which steps to run
       PATHS: ${{ true }}
       BUILD: ${{ true }}
       RUBY_UNIT: ${{ false }}
       JS_UNIT: ${{ true }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # pwd: /home/runner/work/chemotion_ELN/chemotion_ELN
      - name: paths
        if: env.PATHS == 'true'
        run: |
             mkdir .bundle/ vendor/bundle/ node_modules/
             mkdir -p ~/shared/bundle/
             mv ~/shared/bundle/ ~/shared/bundle.bak/
             mv vendor/bundle/  ~/shared/
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          # bundler: 1.17.3
          #bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      #- name: manual install rdkit_chem
       # run: |
        #     gem install rdkit_chem
         #    bundle update rdkit_chem
      - name: build 
        if: env.BUILD == 'true'
        run: |
             npm install
      # new
      - name: after_script
        run: |
              if test -d "vendor/bundle"; then mv vendor/bundle ~/shared/vendor.bak; fi
              mv ~/shared/bundle/ vendor/

      - name: ruby unit test
        if: env.RUBY_UNIT == 'true'
        run: |
            RAILS_ENV=test bundle exec rake db:schema:load --trace
            
      - uses: actions/setup-node@v1
      
      - name: js unit test
        if: env.JS_UNIT == 'true'
        run: |
            RAILS_ENV=test bundle exec rake db:test:prepare && npm test
            
            

